#!/bin/sh
#
# This a script that builds LYSA.

function ggit_branch {
    git branch &> /dev/null
    if [[ $? -eq 0 ]]; then
      echo $(git branch | \grep \* | sed "s/^\* //")
    fi
}

prj_root=$(pwd)
cbranch=$(ggit_branch)
ghp=$prj_root/ghp

RUNHS=$(which runhaskell)

if [ "" == "RUNHS" ]; then
    printf "You need to install GHC and cabal-install.\n"
    printf "See https://github.com/bitemyapp/learnhaskell\n"
    exit 1
fi

if [ ! -d $ghp ]; then
    printf "You have to clone your personal gh-pages branch into ${ghp}.\n"
    printf "You can do this with:\n\t"
    printf "git clone YOUR_REMOTE_REPO -b gh-pages ghp\n"
    exit 1
fi

cd site
$RUNHS main.hs clean
$RUNHS main.hs build

cp -r _site/* $ghp
cd $ghp
git add -A .
git commit -m "$(date), see ${cbranch} branch."
git push
cd $prj_root
