#!/bin/sh
#
# Copyright © 2015, Peter Harpending. <peter@harpending.org>
# 
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and this
# notice are preserved.  This file is offered as-is, without any warranty.

linguas="en ru"

faildie () {
    printf $@
    exit 1
}

en () {
  cd en
  ./build
}

ru () {
  cd ru
  ./build
}

pdfs () {
  cd pdf
  ./deploy-pdf $@
}

pdf_bootstrap () {
  cd pdf
  git clone git@github.com:learnyou/pdfs.git
}

mkpdf () {
    for i in $@ ; do
        $i || faildie "Language does not exist: " ${i}
    done
}

case $1 in
    mkpdf)
        mkpdf $@
        ;;
    bootstrap)
        pdf_bootstrap
        ;;
    pubnightly)
        pdfs $@
        ;;
    *)
        printf "Available commands:\n"
        printf "\tbootstrap\t\t\tClone the pdfs repo (do this only if you want to deploy nightlies, i.e. use lysabuild pubnightly)\n"
        printf "\tmkpdf [lang1 [lang2 ...]]\tmake PDFs for each specified language. If you don't know what to do, this is probably what you should do.\n"
        printf "\tpubnightly [lang1 [lang2 ...]]\tpublish a nightly for each specified language. Assumes you have run \"lysabuild mkpdf [lang1 ...] beforehand\n" 
        printf "\nAvailable languages are:\n"
        printf "\ten\tAmerican English\n"
        printf "\tru\tрусский\n"
esac
