#!/bin/sh

clean_and_die() {
  cd $orig_dir
  rm -rf tmp
  exit $1
}

orig_dir=$(pwd)
mkdir tmp

cp -rvf lysa.ltx chapters/* bibliographies/* images/* tmp/
cd tmp

xelatex lysa.ltx || clean_and_die 1
bibtex lysa
xelatex lysa.ltx && xelatex lysa.ltx

cp lysa.pdf ..
clean_and_die 0
